/**
 * Every sentence the page says, in one place.
 *
 * Views never contain prose: they ask `t(key, vars)`. A template with `|`
 * carries one form per number ("{n} thought|{n} thoughts"), and `{n}` is
 * substituted in the one that fits. Thought labels are never touched: they
 * are the person's own words.
 */

const STRINGS = {
  // navigation
  "nav.home": "Home",
  "nav.thoughts": "My thoughts",
  "nav.people": "People",
  "nav.talk": "Conversations",
  "nav.groups": "Groups",
  "nav.connect": "Connect a chat",
  "nav.skip": "Skip to content",
  "nav.new": "new",

  // account
  "account.signin": "Sign in",
  "account.signout": "Sign out",
  "account.seen_as": "Others see you as",
  "account.signed_in_as": "You signed in as",
  "account.only_you": "Only you see this. It is how you get back to this account from another device or another chat.",
  "account.browser_only": "There is no sign-in on this deployment, so this account lives in this browser only.",
  "account.pseudonym_note": "This is the only name anyone here can see. Your real name and your address are never shown.",
  "account.colours": "Colours",
  "account.theme.light": "Light",
  "account.theme.dark": "Dark",
  "account.theme.system": "Match device",
  "account.language": "Language",
  "account.menu": "Account",

  // states
  "loading": "Loading…",
  "error.generic": "Something went wrong: {message}",
  "error.retry": "Try again",
  "notice.close": "Close",
  "copied": "Copied",

  // home
  "home.title": "Find the people already thinking about what you are thinking about.",
  "home.lede": "Describe the idea, project or question you are working on. Resonance compares the reasoning behind it with what other people have shared, and finds the ones whose thinking overlaps with yours: the same problem, one piece of it, or the same shape in a different field.",
  "home.then": "Then you can talk, think it through together, and form a group around one idea, where everyone works on the whole or on their own part of it.",
  "home.step1.title": "Share a thought",
  "home.step1.body": "In your own words, here or from the chat you already use. Only the structure of the reasoning becomes visible, never your text or your name.",
  "home.step2.title": "See who resonates",
  "home.step2.body": "The match is computed, not judged. Every result shows why: which ideas correspond and which links you both keep.",
  "home.step3.title": "Meet and work together",
  "home.step3.body": "Ask for an introduction. When both agree, you can talk, and open a group where more people join around the same idea.",
  "home.cta.signin": "Sign in to start",
  "home.cta.share": "Share a thought",
  "home.cta.connect": "Or connect the chat you already use",
  "home.signin_why": "Resonance keeps looking after you leave and introduces people to each other. Both need an account it can come back to. Other people only ever see a pseudonym.",
  "home.whats_new": "What's new",
  "home.quiet": "Nothing new since you last looked. Your thoughts keep looking for people.",
  "home.summary.thoughts": "{n} thought|{n} thoughts",
  "home.summary.discoverable": "{n} discoverable",
  "home.summary.people": "{n} person found|{n} people found",
  "home.summary.talks": "{n} conversation|{n} conversations",
  "home.summary.groups": "{n} group|{n} groups",
  "home.news.arrived": "Someone new resonates with “{topic}”",
  "home.news.existing": "{who} was already here when you shared “{topic}”",
  "home.news.request": "{who} asks to be introduced",
  "home.news.invite": "{who} invites you to the group “{title}”",
  "home.news.group_new": "{n} new contribution in “{title}”|{n} new contributions in “{title}”",
  "home.news.in": "in {domain}",
  "home.news.see": "See who",
  "home.news.answer": "Answer",
  "home.news.open": "Open",
  "home.news.dismiss": "Dismiss",
  "home.news.reason.arrived": "arrived after you shared",
  "home.news.reason.existing": "already here",
  "home.news.match": "Match {score}",

  // thoughts
  "thoughts.title": "My thoughts",
  "thoughts.lede": "Each thought is searched on its own. You can share several and withdraw any of them without touching the others.",
  "thoughts.empty": "You have not shared anything yet.",
  "thoughts.new": "Share a new thought",
  "thoughts.composer.label": "What are you working on, and what is hard about it?",
  "thoughts.composer.placeholder": "Say what causes what, what prevents what, what requires what. For example: “A partial outage causes synchronized client retries. The retries cause request amplification. Jittered backoff prevents the amplification.”",
  "thoughts.composer.hint": "Write in English for now: thoughts are compared in one index, and other languages are not read yet. Your text is not kept; only the structure below is.",
  "thoughts.composer.extract": "Show what would be shared",
  "thoughts.composer.reading": "Reading the structure…",
  "thoughts.composer.preview": "This is all anyone will ever see",
  "thoughts.composer.share": "Share and start looking",
  "thoughts.composer.back": "Change the text",
  "thoughts.composer.cancel": "Cancel",
  "thoughts.composer.nothing": "No structure could be read from this text. Say what causes what, what prevents what, what requires what.",
  "thoughts.state.discoverable": "Discoverable",
  "thoughts.state.private": "Private",
  "thoughts.state.withdrawn": "Withdrawn",
  "thoughts.state.discoverable.hint": "People whose reasoning overlaps can find it, and it keeps looking for them.",
  "thoughts.state.private.hint": "Prepared, never shared. Nobody can see it.",
  "thoughts.state.withdrawn.hint": "Was shared; not any more. It is not reported to anyone.",
  "thoughts.shared_at": "Shared {when}",
  "thoughts.prepared_at": "Prepared {when}",
  "thoughts.withdrawn_at": "Withdrawn {when}",
  "thoughts.people": "See who resonates",
  "thoughts.stop": "Stop sharing",
  "thoughts.stop.confirm": "Stop sharing this thought? It stops being visible and stops looking for people. Your other thoughts are untouched.",
  "thoughts.stop.yes": "Yes, stop",
  "thoughts.stop.no": "Keep sharing",
  "thoughts.structure": "Structure",
  "thoughts.ideas": "{n} idea|{n} ideas",
  "thoughts.links": "{n} link|{n} links",
  "thoughts.field": "Field",

  // people
  "people.title": "People",
  "people.lede": "Everyone found for a thought of yours, with the reason. Nobody here knows about you until you ask for an introduction and they agree.",
  "people.for": "For the thought",
  "people.none_shared": "Share a thought first, and the people whose reasoning overlaps with it appear here.",
  "people.empty.title": "Nobody yet, and that is usual at the start.",
  "people.empty.body": "Your thought stays out there. Everyone who arrives after you is checked against it, and you will find them here and in any chat you have connected.",
  "people.found": "{n} person|{n} people",
  "people.near": "{n} near miss|{n} near misses",
  "people.near.hint": "Similar skeletons the engine will not call a resonance, or the same link running the other way.",
  "people.select": "Select someone to see why they resonate.",
  "people.why": "Why this resonates",
  "people.correspond": "What corresponds",
  "people.yours": "Yours",
  "people.theirs": "Theirs",
  "people.kept": "{n} link both of you keep|{n} links both of you keep",
  "people.contradictions": "{n} contradiction|{n} contradictions",
  "people.strength": "Structural match",
  "people.confidence.high": "high confidence",
  "people.confidence.medium": "medium confidence",
  "people.confidence.low": "low confidence",
  "people.ask": "Ask for an introduction",
  "people.asked": "Introduction requested",
  "people.connected": "Connected",
  "people.declined": "Declined",
  "people.open_talk": "Open the conversation",
  "people.ask.label": "A few words for {who}. They see only this, and your pseudonym.",
  "people.ask.placeholder": "What in their thought caught you, and what you would like to talk about.",
  "people.ask.send": "Send the request",
  "people.ask.sent": "Sent. Nothing opens until they agree.",
  "people.example": "example from the seeded corpus",
  "people.reject.direction": "the same link, running the opposite way",
  "people.reject.relation_type": "the same two ideas, joined by a different kind of link",
  "people.reject.other": "the structures clash",
  "people.strength.very_close": "very close",
  "people.strength.close": "close",
  "people.strength.partial": "partial",
  "people.strength.faint": "faint",

  // verdicts
  "verdict.direct": "the same thing, and they are working on it too",
  "verdict.approximate": "close — some of it lines up",
  "verdict.analogical": "same shape, different subject",
  "verdict.complementary": "what you are missing is what they work on",
  "verdict.negative": "not called a resonance",

  // talk
  "talk.title": "Conversations",
  "talk.lede": "Introductions need both sides. Nothing opens until the other person agrees, and no contact details are ever exchanged.",
  "talk.requests": "Requests",
  "talk.incoming": "{who} asks to be introduced",
  "talk.outgoing": "You asked {who}",
  "talk.waiting": "waiting for their answer",
  "talk.accept": "Accept",
  "talk.decline": "Decline",
  "talk.cancel": "Withdraw the request",
  "talk.declined": "declined",
  "talk.cancelled": "withdrawn",
  "talk.list": "People you talk to",
  "talk.empty": "No conversations yet. Find someone on the People page and ask for an introduction.",
  "talk.pick": "Pick a conversation.",
  "talk.relay": "Relay only: no contact details are exchanged. Only what is typed here is passed on.",
  "talk.send": "Send",
  "talk.placeholder": "Write to {who}",
  "talk.nothing_yet": "Nothing written yet. Say hello.",
  "talk.open_group": "Open a group with {who}",
  "talk.their_words": "Their words, shown as written.",
  "talk.you": "You",

  // groups
  "groups.title": "Groups",
  "groups.lede": "A group gathers people around one idea. Everyone can talk, split the work into parts, and add what they now understand, so the group can see where it agrees and where it still disagrees.",
  "groups.empty": "No groups yet. A group starts from a conversation: open one with someone you are connected to.",
  "groups.invitations": "Invitations",
  "groups.invite.line": "{who} invites you to “{title}”",
  "groups.invite.join": "Join",
  "groups.invite.later": "Not now",
  "groups.new": "New group",
  "groups.new.with": "Start from a conversation with",
  "groups.new.title": "Name of the group",
  "groups.new.brief": "What the group is about, in a few sentences",
  "groups.new.create": "Create the group",
  "groups.new.none": "You need at least one accepted introduction to start a group.",
  "groups.members": "{n} member|{n} members",
  "groups.new_for_you": "{n} new",
  "groups.open": "Open",
  "group.back": "All groups",
  "group.tab.discussion": "Discussion",
  "group.tab.parts": "Parts of the work",
  "group.tab.understanding": "Shared understanding",
  "group.tab.members": "Members",
  "group.role.owner": "started the group",
  "group.role.member": "member",
  "group.role.invited": "invited, not joined yet",
  "group.you": "you",
  "group.post.placeholder": "Write to the group",
  "group.post.send": "Post",
  "group.post.empty": "Nothing posted yet.",
  "group.parts.lede": "Split the idea into parts, and let people take the one they work on.",
  "group.parts.add": "Add a part",
  "group.parts.placeholder": "A part of the idea, e.g. “power supply” or “route planning”",
  "group.parts.empty": "No parts yet.",
  "group.parts.todo": "open",
  "group.parts.doing": "in progress",
  "group.parts.done": "done",
  "group.parts.take": "Take it",
  "group.parts.finish": "Mark done",
  "group.parts.reopen": "Reopen",
  "group.understanding.lede": "Each member adds the structure of what they now understand. The group then shows where the accounts agree, where they contradict each other, and what is still unanswered.",
  "group.understanding.add": "Add what you now understand",
  "group.understanding.placeholder": "In your own words: what causes what, what prevents what.",
  "group.understanding.note": "A short note for the others (optional)",
  "group.understanding.show": "Show the structure",
  "group.understanding.submit": "Add to the group",
  "group.understanding.use_thought": "Use the thought you shared",
  "group.understanding.empty": "Nothing added yet. What you add first is what the others will read.",
  "group.understanding.standing": "Where the group stands",
  "group.understanding.first": "Add your own understanding first, and the group can say where it agrees with yours.",
  "group.understanding.with": "With {who}",
  "group.understanding.agreed": "Agreed",
  "group.understanding.contested": "Contested",
  "group.understanding.yours_open": "Yours, unanswered",
  "group.understanding.theirs_open": "Theirs, unanswered",
  "group.understanding.by": "{who}, {when}",
  "group.invite": "Invite someone you are connected to",
  "group.invite.send": "Invite",
  "group.invite.none": "Everyone you are connected to is already here, or you have no other connections yet.",
  "group.leave": "Leave the group",

  // connect
  "connect.title": "Connect a chat",
  "connect.lede": "Resonance works from the conversation you are already having. Give your assistant one address, and it can share your thought, look for people, ask for introductions and read replies, always with your approval.",
  "connect.address": "The address",
  "connect.copy": "Copy",
  "connect.note": "This is the only thing a client needs; it finds the sign-in by itself. You are never asked to paste a key.",
  "connect.same_account": "Every route is the same account: a thought shared from a chat is the thought this page shows.",
  "connect.tab.claude": "Claude",
  "connect.tab.chatgpt": "ChatGPT",
  "connect.tab.grok": "Grok",
  "connect.tab.cli": "Claude Code",
  "connect.tab.json": "Cursor & others",
  "connect.tab.browser": "This browser",
  "connect.steps.claude": "Settings → Connectors → Add custom connector → paste the address.",
  "connect.steps.chatgpt": "Settings → Apps & Connectors → Advanced → Developer mode → Create → paste the address, authentication OAuth → Scan tools. Developer mode is not on every plan.",
  "connect.steps.grok": "Connectors → New Connector → Custom → paste the address.",
  "connect.steps.json": "Any client that reads an mcp.json:",
  "connect.steps.browser.yes": "This browser has WebMCP: the tools on this page are registered through document.modelContext right now, with no connector at all.",
  "connect.steps.browser.no": "This browser does not expose document.modelContext, so nothing is registered here. Chrome 152 exposes it when started with --enable-features=WebMCP. The connectors above reach the same product.",
  "connect.ask.title": "Then just ask, in your own words",
  "connect.ask.1": "“I have been working through this idea — are there people here thinking along the same lines?”",
  "connect.ask.2": "“Find everyone working on something close to this, so we could pull together into one group.”",
  "connect.ask.3": "“Has anyone new turned up for the thought I shared last week?”",
  "connect.ask.note": "Your assistant shows you the structure it would share, and shares only once you approve.",

  // common
  "time.now": "just now",
  "time.minutes": "{n} min ago",
  "time.hours": "{n} h ago",
  "time.days": "{n} d ago",
  "footer.claim": "The match is computed, not judged: no language model decides who resonates with you, and you are shown the working.",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.support": "Support",
};

export function t(key, vars = {}) {
  let template = STRINGS[key];
  if (template === undefined) return key;
  if (template.includes("|") && "n" in vars) {
    const forms = template.split("|");
    const n = Math.abs(Math.trunc(Number(vars.n) || 0));
    template = forms[n === 1 ? 0 : Math.min(1, forms.length - 1)];
  }
  return template.replace(/\{(\w+)\}/g, (_, name) => (name in vars ? String(vars[name]) : `{${name}}`));
}

export function has(key) {
  return key in STRINGS;
}

export { STRINGS };
