"""Repository protocol. Storage implementations must not score thoughts.

This is an internal data-layer seam. Authenticated subject/object authorization
belongs to R12/R12B and is the only transport-facing mutation boundary.
"""

from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence

from .models import (
    AuditEvent,
    IdempotencyKey,
    IdempotencyRecord,
    SessionRecord,
    UserRecord,
)


class PersistenceRepository(Protocol):
    backend_name: str

    def migrate(self) -> tuple[str, ...]: ...
    def health(self) -> dict[str, Any]: ...
    def get_corpus_generation(self) -> int: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...

    def put_user(self, user: UserRecord, *, audit: AuditEvent | None = None) -> UserRecord: ...
    def get_user(self, user_id: str) -> UserRecord | None: ...
    def list_users(self) -> Sequence[UserRecord]: ...

    def put_session(
        self,
        session: SessionRecord,
        *,
        expected_version: int | None = None,
        idempotency: IdempotencyKey | None = None,
        audit: AuditEvent | None = None,
    ) -> SessionRecord: ...

    def get_session(self, session_id: str) -> SessionRecord | None: ...
    def get_session_by_thought(self, thought_id: str) -> SessionRecord | None: ...
    def list_sessions(self, *, include_deleted: bool = False) -> Sequence[SessionRecord]: ...
    def list_discoverable_sessions(self) -> Sequence[SessionRecord]: ...

    def lookup_idempotency(self, key: IdempotencyKey) -> SessionRecord | None: ...
    def list_idempotency(self) -> Sequence[IdempotencyRecord]: ...

    def append_audit(self, event: AuditEvent) -> AuditEvent: ...
    def list_audit(self) -> Sequence[AuditEvent]: ...

    def export_payload(self) -> dict[str, Any]: ...
    def import_payload(self, payload: Mapping[str, Any]) -> None: ...
