"""Hand-authored lexicon of abstract relational concepts.

This is the deterministic, inspectable replacement for "ask an embedding model
whether two labels mean the same thing". Every concept class names a
domain-independent *relational* notion (accumulation, depletion, cascade,
constraint, ...) and lists the surface forms that realise it in ordinary
prose. Matching is done on stems (Porter for Latin script, Snowball Russian
for Cyrillic), so only base forms are needed.

A concept class is not English; only its surface forms are. Each class
therefore lists the English forms first and the Russian forms after them, in
one tuple, so the class reads as one idea in two languages. The two alphabets
do not overlap and are stemmed by different algorithms, so a term in one can
never match a token in the other: adding a language is additive by
construction. `ops/lexicon_check.py` asserts that rather than assuming it.

The lexicon is versioned; changing it changes fingerprint/config hashes.

Design rule: a class is admitted only if it is *the kind of thing* that can
correspond across domains in an analogy. Domain nouns (battery, hospital)
belong to the DOMAIN classes at the end and never carry analogical weight;
they only support same-domain (direct) resonance.
"""

from __future__ import annotations

from .stem import stem

LEXICON_VERSION = "resonance-lexicon/0.3.0"

# concept -> (role_hint | None, terms)
# role_hint feeds extraction and soft role compatibility; None = no hint.
CONCEPTS: dict[str, tuple[str | None, tuple[str, ...]]] = {
    # ---- accumulation / depletion dynamics -------------------------------
    "ACCUMULATION": ("state", ("accumulate", "accumulation", "buildup", "build up", "build-up", "pile up",
                               "pileup", "backlog", "stockpile", "amass", "hoard", "gather", "mount up",
                               "mounting", "heap", "overflow", "glut", "excess", "surplus", "congest",
                               "congestion", "clog", "silt up", "sediment", "residue",
                               "накопление", "накапливать", "копить", "скопление", "скапливаться", "нарастание",
                               "нарастать", "груда", "куча", "завал", "переполнение", "избыток", "излишек",
                               "засорение", "отложение", "осадок", "залежи", "невыполненные задачи")),
    "DEPLETION": ("state", ("deplete", "depletion", "exhaust", "exhaustion", "drain", "run out", "shortage",
                            "scarcity", "scarce", "starve", "starvation", "deficit", "dwindle", "erode",
                            "erosion", "attrition", "run dry", "burn through", "underfund",
                            "истощение", "истощать", "исчерпание", "исчерпать", "иссякать", "иссякнуть",
                            "опустошение", "опустошать", "убыль", "убывание", "эрозия", "размывание", "отток",
                            "текучесть кадров", "на исходе", "выработанный", "недофинансирование")),
    "GROWTH": ("state", ("grow", "growth", "increase", "rise", "rising", "expand", "expansion", "escalate",
                         "escalation", "surge", "spike", "swell", "inflate", "climb", "boom", "scale up",
                         "proliferate", "proliferation", "multiply",
                         "рост", "расти", "увеличение", "увеличивать", "возрастание", "возрастать", "прирост",
                         "подъем", "расширение", "расширяться", "разрастание", "разрастаться", "эскалация", "бум",
                         "взлет", "набухание", "размножение", "множиться", "масштабирование")),
    "DECLINE": ("state", ("decline", "decrease", "drop", "fall", "falling", "shrink", "contract",
                          "contraction", "slump", "diminish", "reduce", "reduction", "lower", "wane",
                          "recede", "taper", "slow down", "slowdown", "downturn",
                          "снижение", "снижать", "спад", "падение", "падать", "уменьшение", "уменьшать",
                          "сокращение", "сокращать", "сжатие", "угасание", "угасать", "просадка", "проседание",
                          "замедление", "на убыль", "нисходящий")),
    "DEGRADATION": ("state", ("degrade", "degradation", "deteriorate", "deterioration", "decay", "wear",
                              "wear out", "worn", "corrode", "corrosion", "rot", "fatigue", "weaken",
                              "weakening", "impair", "impairment", "breakdown", "break down", "fray",
                              "rust", "aging", "ageing", "obsolescence", "erosion of",
                              "деградация", "деградировать", "ухудшение", "ухудшать", "износ", "изнашиваться",
                              "изношенный", "порча", "гниение", "гнить", "коррозия", "ржавчина", "ржаветь",
                              "старение", "стареть", "обветшание", "обветшать", "ослабление", "ослабевать",
                              "устаревание", "разрушаться", "ветшать")),
    "SATURATION": ("state", ("saturate", "saturation", "full", "at capacity", "maxed out", "overload",
                             "overloaded", "overwhelm", "overwhelmed", "swamped", "oversubscribed",
                             "exceed capacity", "tipping point", "critical mass",
                             "насыщение", "насыщать", "перенасыщение", "заполненность", "заполнен", "битком",
                             "под завязку", "критическая масса", "точка перелома", "точка невозврата",
                             "предел вместимости", "захлебываться", "не справляться", "выше крыши")),
    "LEAK": ("mechanism", ("leak", "leakage", "seep", "seepage", "escape", "spill", "spillage", "bleed",
                           "loss of", "drip", "lossy",
                           "утечка", "утекать", "протечка", "протекать", "просачивание", "просачиваться",
                           "подтекать", "разлив", "испарение", "улетучиваться", "подтекание", "сочиться")),
    # ---- flow / throughput --------------------------------------------------
    "FLOW": ("mechanism", ("flow", "stream", "throughput", "traffic", "circulate", "circulation", "transfer",
                           "transmission", "transmit", "pass through", "conduct", "conduction", "pipeline",
                           "channel", "movement of",
                           "поток", "течение", "движение", "циркуляция", "циркулировать", "передача", "передавать",
                           "перенос", "пропускание", "прохождение", "проходить", "трафик", "канал", "русло",
                           "транзит", "проводимость", "проводить", "трубопровод")),
    "BOTTLENECK": ("constraint", ("bottleneck", "chokepoint", "choke point", "single point", "narrow",
                                  "constriction", "queue", "queueing", "waiting line", "backpressure",
                                  "back pressure", "contention", "serialization point",
                                  "узкое место", "бутылочное горлышко", "горлышко", "сужение", "сужаться", "очередь",
                                  "единая точка", "единственная точка", "единственный канал", "затык",
                                  "конкуренция за ресурс", "борьба за ресурс", "стояние в очереди")),
    "BLOCKAGE": ("state", ("block", "blockage", "blocked", "obstruct", "obstruction", "jam", "stall",
                           "stalled", "stuck", "deadlock", "gridlock", "halt", "freeze", "frozen",
                           "clot", "impasse", "standstill", "traffic jam", "tailback", "spillback", "lock", "locked", "lock-in", "lock in", "lockout", "treatment lock", "hold", "on hold",
                           "блокировка", "блокировать", "заблокировать", "пробка", "затор", "засор", "застой", "застревать",
                           "застрять", "зависание", "зависать", "тупик", "взаимоблокировка", "остановка", "паралич",
                           "заморозка", "заморозить", "заклинивание", "стопор", "непроходимость", "намертво")),
    "DELAY": ("state", ("delay", "latency", "lag", "slow", "slowness", "wait", "waiting", "postpone",
                        "postponement", "late", "lateness", "overdue", "response time", "turnaround",
                        "sluggish", "backlog of requests", "time to", "slower", "slowing", "slows", "slowed", "sluggish thinking", "slow progress", "cycle time", "lead time", "turnaround time", "time to recover",
                        "задержка", "задерживать", "опоздание", "опаздывать", "опоздать", "промедление", "медлить",
                        "отсрочка", "отложить", "откладывать", "лаг", "запаздывание", "запаздывать", "ожидание",
                        "ждать", "просрочка", "медленный", "вялый", "время отклика", "время ожидания",
                        "время выполнения", "длительность цикла", "срок исполнения")),
    "ACCELERATION": ("mechanism", ("accelerate", "acceleration", "speed up", "faster", "hasten", "expedite",
                                   "quicken", "rush", "fast track", "fast-track",
                                   "ускорение", "ускорять", "разгон", "разгонять", "быстрее", "форсировать",
                                   "форсирование", "подгонять", "торопить", "спешка", "в срочном порядке")),
    # ---- feedback / propagation -------------------------------------------
    "FEEDBACK": ("mechanism", ("feedback", "feedback loop", "loop", "self-reinforcing", "self reinforcing",
                               "vicious cycle", "virtuous cycle", "vicious circle", "reinforce",
                               "reinforcement", "recursive", "compounding", "compound", "snowball",
                               "spiral", "runaway", "positive feedback", "negative feedback",
                               "обратная связь", "петля обратной связи", "петля", "замкнутый круг", "порочный круг",
                               "добродетельный круг", "самоусиление", "самоподдержание", "самоподдерживающийся",
                               "подкрепление", "рекурсия", "рекурсивный", "спираль", "снежный ком",
                               "эффект снежного кома", "раскручиваться", "по кругу")),
    "AMPLIFICATION": ("mechanism", ("amplify", "amplification", "magnify", "magnification", "multiplier",
                                    "multiply", "intensify", "intensification", "exacerbate", "worsen",
                                    "aggravate", "boost", "leverage", "gain", "amplifier",
                                    "усиление", "усиливать", "усилитель", "умножать", "множитель", "обострение",
                                    "обострять", "усугубление", "усугублять", "рычаг", "раздувать", "многократно",
                                    "коэффициент усиления")),
    "CASCADE": ("mechanism", ("cascade", "cascading", "domino", "chain reaction", "knock-on", "knock on",
                              "ripple", "ripple effect", "contagion", "spread", "spreading", "propagate",
                              "propagation", "spillover", "spill over", "avalanche", "run on", "bank run",
                              "panic", "stampede", "herd", "sequential failure", "chain of failures",
                              "каскад", "каскадный", "лавина", "лавинообразный", "домино", "эффект домино",
                              "цепная реакция", "цепочка отказов", "распространение", "распространяться",
                              "расползание", "перекидываться", "заражение", "заражать", "паника", "давка",
                              "стадность", "стадное поведение", "набег вкладчиков", "волновой эффект", "по цепочке")),
    "DAMPING": ("mechanism", ("damp", "damping", "dampen", "attenuate", "attenuation", "absorb", "absorption",
                              "cushion", "buffer against", "smooth", "smoothing", "stabilize", "stabilise",
                              "stabilization", "mitigate", "mitigation", "soften", "moderate", "temper",
                              "suppress", "suppression", "dissipate", "dissipation", "counteract",
                              "counterbalance", "offset", "hedge", "insulate", "insulation",
                              "демпфирование", "демпфер", "гашение", "гасить", "затухание", "затухать", "ослаблять",
                              "поглощение", "поглощать", "амортизатор", "амортизировать", "смягчение", "смягчать",
                              "сглаживание", "сглаживать", "стабилизация", "стабилизировать", "подавление",
                              "подавлять", "рассеивание", "рассеивать", "противодействие", "противовес",
                              "хеджирование", "умерять", "приглушать")),
    "OSCILLATION": ("state", ("oscillate", "oscillation", "swing", "fluctuate", "fluctuation", "volatile",
                              "volatility", "cycle", "cyclical", "periodic", "boom and bust", "seesaw",
                              "overshoot", "undershoot", "hunting", "instability", "unstable", "wobble",
                              "ringing",
                              "колебание", "колебаться", "качание", "флуктуация", "флуктуировать", "волатильность",
                              "цикл", "циклический", "периодический", "чередование", "нестабильность",
                              "неустойчивый", "раскачивание", "раскачиваться", "перерегулирование",
                              "недорегулирование", "маятник")),
    # ---- load / stress / heat --------------------------------------------
    "LOAD": ("state", ("load", "demand", "burden", "workload", "traffic load", "request volume", "volume",
                       "peak", "peak load", "rush", "burst", "spike in", "strain", "usage", "utilization",
                       "utilisation", "throughput demand", "pressure of work", "caseload", "inflow", "influx", "intake", "incoming",
                       "нагрузка", "загрузка", "загруженность", "перегрузка", "перегруженность", "перегружен",
                       "спрос", "объем", "объем запросов", "пик", "пиковая нагрузка", "наплыв", "приток",
                       "поступление", "входящий поток", "интенсивность", "использование", "бремя",
                       "рабочая нагрузка", "поток обращений")),
    "STRESS": ("state", ("stress", "strain", "tension", "pressure", "force", "overexertion", "exertion",
                         "overwork", "overuse", "wear and tear", "duress", "pressurize",
                         "напряжение", "стресс", "стрессовый", "давление", "нажим", "натяжение", "перенапряжение",
                         "перенапрягать", "надрыв", "работа на износ", "сверхурочные", "гнет")),
    "HEAT": ("state", ("heat", "heating", "hot", "thermal", "temperature", "overheat", "overheating",
                       "warm", "warming", "fever", "burn", "burning", "thermal runaway", "hotspot",
                       "hot spot",
                       "нагрев", "нагревание", "нагреваться", "жар", "тепло", "тепловой", "температура", "перегрев",
                       "перегреваться", "горячий", "горение", "гореть", "ожог", "тепловыделение", "разогрев",
                       "тепловой разгон", "очаг перегрева", "лихорадка")),
    "COOLING": ("method", ("cool", "cooling", "cold", "chill", "refrigerate", "refrigeration", "ventilate",
                           "ventilation", "heat sink", "heatsink", "radiator", "dissipate heat",
                           "thermal management", "thermal control", "cool down", "airflow",
                           "охлаждение", "охлаждать", "охладить", "холод", "холодный", "остывание", "остывать",
                           "вентиляция", "вентилировать", "проветривание", "радиатор", "теплоотвод",
                           "кондиционирование", "обдув", "продувка", "отвод тепла", "терморегулирование")),
    "FRICTION": ("mechanism", ("friction", "drag", "resistance", "resistive", "impedance", "viscosity",
                               "inertia", "sticking", "hysteresis", "overhead", "red tape", "bureaucracy", "drag on", "interest drag",
                               "трение", "сопротивление", "вязкость", "инерция", "инерционность", "залипание",
                               "гистерезис", "волокита", "бюрократия", "бумажная волокита", "буксовать",
                               "со скрипом")),
    # ---- capacity / limits / constraints ---------------------------------
    "CAPACITY": ("resource", ("capacity", "bandwidth", "headroom", "slack", "throughput limit",
                              "quota", "allowance", "carrying capacity", "seat", "seats",
                              "slots", "supply of", "availability",
                              "пропускная способность", "емкость", "вместимость", "мощность", "квота", "доступность",
                              "наличие", "свободные места", "места", "слот", "запас мощности", "резерв мощности")),
    "LIMIT": ("constraint", ("limit", "limitation", "cap", "bound", "boundary", "threshold", "maximum",
                             "minimum", "restriction", "restrict",
                             "hard limit", "rate limit", "budget cap", "cutoff", "cut-off", "tolerance",
                             "envelope", "upper bound", "lower bound", "capacity limit", "spillway", "hiring freeze", "headcount freeze", "spending freeze", "freeze on",
                             "ограничение", "ограничивать", "лимит", "предел", "предельный", "граница", "порог",
                             "максимум", "минимум", "потолок", "рамки", "верхняя граница", "нижняя граница",
                             "жесткий лимит", "допуск", "отсечка", "заморозка найма", "ограничение скорости")),
    "BUDGET": ("constraint", ("budget", "allocation", "allowance", "funding", "funds", "money", "cost",
                              "expense", "spending", "price", "pricing", "fee", "cash", "capital",
                              "financial", "afford", "affordability", "runway",
                              "бюджет", "смета", "финансирование", "финансы", "средства", "деньги", "стоимость",
                              "затраты", "расходы", "издержки", "цена", "ценообразование", "тариф", "плата",
                              "комиссия", "наличные", "капитал", "финансовый", "позволить себе", "по карману",
                              "запас средств")),
    "DEADLINE": ("constraint", ("deadline", "time limit", "timeline", "schedule", "due date", "cutoff date",
                                "time budget", "time window", "timebox", "sprint", "quarter end",
                                "expiry", "expiration", "expire", "end of quarter", "launch date", "ship date", "release date", "quarterly earnings", "exam week", "reporting date", "completion deadline", "shipping deadline", "release deadline", "cutoff",
                                "срок", "дедлайн", "крайний срок", "предельный срок", "график", "расписание",
                                "дата сдачи", "дата запуска", "дата релиза", "временное окно", "спринт",
                                "конец квартала", "истечение срока", "истекать", "сдача проекта", "отчетная дата")),
    "SCARCITY": ("constraint", ("scarce", "scarcity", "limited supply", "shortage", "rare", "rarity",
                                "insufficient", "lack", "lacking", "not enough", "too few", "understaffed",
                                "shorthanded", "short-handed", "constrained supply",
                                "нехватка", "недостаток", "дефицит", "дефицитный", "скудность", "скудный",
                                "редкость", "редкий", "недостаточно", "не хватать", "кадровый голод",
                                "недоукомплектованность", "слишком мало")),
    "REDUNDANCY": ("method", ("redundancy", "redundant", "backup", "spare", "failover", "fallback",
                              "replica", "replication", "duplicate", "mirror", "reserve", "reserves",
                              "safety margin", "margin of safety", "slack capacity", "buffer stock",
                              "buffer", "cushion", "contingency", "insurance",
                              "резервирование", "резерв", "резервный", "запас", "запасной", "дублирование",
                              "дублировать", "дубликат", "реплика", "репликация", "зеркало", "зеркалирование",
                              "подстраховка", "страховка", "страхование", "буфер", "подушка безопасности",
                              "запас прочности", "горячий резерв", "на всякий случай")),
    # ---- coupling / structure --------------------------------------------
    "DEPENDENCY": ("constraint", ("depend", "dependency", "dependence", "dependent", "rely", "reliance",
                                  "prerequisite", "precondition", "requirement", "require", "need", "needs",
                                  "contingent on", "hinge on", "hinges on", "predicated on", "upstream",
                                  "downstream", "chain of",
                                  "зависимость", "зависеть", "полагаться", "опора на", "предпосылка",
                                  "предварительное условие", "требование", "требовать", "необходимость", "нужно",
                                  "нужен", "обусловлен", "завязан на", "выше по цепочке", "ниже по цепочке",
                                  "цепочка зависимостей", "упирается в")),
    "COUPLING": ("mechanism", ("couple", "coupling", "coupled", "tightly coupled", "interlock",
                               "interlocked", "entangle", "entanglement", "interdependent", "interdependence",
                               "linked", "link", "connection", "connected", "bind", "binding", "tie",
                               "tied", "wired together", "monolith", "monolithic", "integration", "interconnected", "interconnect", "interconnection", "shared", "sharing", "monoculture", "uniform", "homogeneous", "single shared", "entangled",
                               "связанность", "связность", "сцепление", "сцеплен", "жесткая связь", "тесная связь",
                               "переплетение", "переплетен", "взаимозависимость", "взаимосвязь", "соединение",
                               "соединен", "связка", "монолит", "монолитный", "однородность", "унификация",
                               "монокультура", "интеграция", "общий", "совместное использование",
                               "завязаны друг на друга")),
    "ISOLATION": ("method", ("isolate", "isolation", "isolated", "decouple", "decoupling", "separate",
                             "separation", "partition", "quarantine", "compartment", "compartmentalize",
                             "bulkhead", "firewall", "silo", "sandbox", "containment", "contain", "modular",
                             "modularity", "loosely coupled", "ring fencing", "ring fence", "ring fenced", "islanding", "island", "diversification", "diversify", "diversified", "segregate", "segregation", "air gap", "airgap", "buffer zone", "buffer zones",
                             "изоляция", "изолировать", "разделение", "разделять", "развязка", "развязать",
                             "обособление", "обособить", "разграничение", "отделение", "отделять", "карантин",
                             "отсек", "переборка", "брандмауэр", "песочница", "сегментация", "сегрегация",
                             "модульность", "слабая связанность", "диверсификация", "диверсифицировать",
                             "воздушный зазор", "буферная зона", "локализация", "локализовать")),
    "FRAGMENTATION": ("state", ("fragment", "fragmentation", "fragmented", "scattered", "dispersed",
                                "dispersion", "splinter", "split", "divided", "division", "disjoint",
                                "siloed", "sprawl", "sprawling", "uncoordinated", "disorganized",
                                "фрагментация", "фрагментированный", "раздробленность", "дробление", "раздробить",
                                "разрозненность", "разобщенность", "распыление", "распылен", "расщепление", "раскол",
                                "расколот", "разброд", "нескоординированность", "неорганизованность", "хаотичность",
                                "вразнобой", "кто во что горазд")),
    "COORDINATION": ("mechanism", ("coordinate", "coordination", "synchronize", "synchronization", "sync",
                                   "align", "alignment", "orchestrate", "orchestration", "cooperate",
                                   "cooperation", "collaborate", "collaboration", "consensus", "agreement",
                                   "handoff", "hand-off", "hand off", "scheduling", "arbitration",
                                   "consistency", "coherence", "coherent", "teamwork", "registry", "shared registry", "contract", "single source of truth", "handoff protocol", "sync meeting", "alignment sync", "alignment meeting",
                                   "координация", "координировать", "согласование", "согласовывать", "синхронизация",
                                   "синхронизировать", "оркестрация", "взаимодействие", "сотрудничество",
                                   "сотрудничать", "кооперация", "совместная работа", "командная работа",
                                   "консенсус", "договоренность", "соглашение", "передача дел", "передача смены",
                                   "единый источник истины", "общий реестр", "реестр", "стыковка", "слаженность")),
    "MISALIGNMENT": ("problem", ("misalign", "misalignment", "misaligned", "mismatch", "mismatched",
                                 "inconsistent", "inconsistency", "incoherent", "incoherence", "out of sync",
                                 "desync", "drift apart", "divergence", "diverge", "contradiction",
                                 "conflict", "conflicting", "clash", "disagreement", "disagree",
                                 "skew", "skewed", "discrepancy", "different directions", "pulling apart", "at odds", "cross purposes", "clashing",
                                 "рассогласование", "несогласованность", "несоответствие", "расхождение", "разнобой",
                                 "противоречие", "конфликт", "конфликтовать", "несовпадение", "разногласие",
                                 "разлад", "рассинхронизация", "рассинхрон", "перекос", "в разные стороны",
                                 "тянуть в разные стороны", "не совпадает")),
    "NOISE": ("problem", ("noise", "noisy", "interference", "distortion", "jitter", "static", "clutter",
                          "spurious", "false alarm", "false positive", "garbage", "junk", "irrelevant",
                          "distraction", "distract", "chatter",
                          "шум", "шумный", "помехи", "искажение", "искажать", "дрожание", "джиттер", "мусор", "хлам",
                          "посторонний", "ложная тревога", "ложное срабатывание", "ложноположительный", "отвлечение",
                          "отвлекать", "болтовня", "лишнее", "нерелевантный", "не по делу")),
    "SIGNAL": ("evidence", ("signal", "indicator", "symptom", "marker", "cue", "sign", "warning",
                            "warning sign", "early warning", "alarm", "alert", "telemetry", "metric",
                            "reading", "measurement", "measure", "sensor", "gauge", "detect", "detection",
                            "observation", "observe", "monitor", "monitoring", "records", "statistics", "dashboard", "burn rate", "valuation", "mark to market", "appraisal", "readings", "report", "reports", "chart", "graph", "plot", "log", "logs", "counts", "interferometry", "spectroscopy", "imaging", "scan", "scanner", "trace", "traces", "probe readings",
                            "сигнал", "индикатор", "показатель", "показания", "симптом", "признак", "маркер", "знак",
                            "предупреждение", "ранний признак", "тревога", "оповещение", "метрика", "измерение",
                            "датчик", "сенсор", "счетчик", "обнаружение", "обнаружить", "мониторинг", "отслеживание",
                            "приборная панель", "телеметрия", "сводка")),
    "UNCERTAINTY": ("state", ("uncertain", "uncertainty", "ambiguous", "ambiguity", "unknown", "unclear",
                              "vague", "fuzzy", "unpredictable", "unpredictability", "variance",
                              "randomness", "random", "stochastic", "guess", "guessing", "doubt", "undiagnosed", "unexplained", "unknown cause", "blind", "invisible", "hidden cause", "unknown origin", "disputed", "unresolved", "mystery", "puzzling", "blind spots",
                              "неопределенность", "неясность", "неясный", "неизвестность", "двусмысленность",
                              "размытость", "туманный", "непредсказуемость", "случайность", "вероятностный",
                              "гадать", "сомнение", "сомневаться", "необъяснимый", "невыясненный",
                              "непонятная причина", "вслепую", "спорный", "нерешенный", "загадка",
                              "неизвестная причина")),
    "ERROR": ("problem", ("error", "mistake", "bug", "defect", "fault", "faulty", "flaw", "flawed",
                          "glitch", "malfunction", "incorrect", "wrong", "inaccurate", "inaccuracy",
                          "miscalculation", "misread", "typo", "corruption", "corrupt", "invalid", "bad loan", "bad debt", "nonperforming loan", "non performing loan",
                          "ошибка", "ошибочный", "ошибаться", "погрешность", "дефект", "брак", "бракованный", "баг",
                          "сбой", "неисправность", "изъян", "недочет", "неверный", "неправильный", "некорректный",
                          "неточность", "просчет", "опечатка", "повреждение данных", "порча данных",
                          "недействительный")),
    "DRIFT": ("state", ("drift", "drifting", "creep", "gradual shift", "slippage", "slip", "deviation",
                        "deviate", "wander", "scope creep", "shift over time", "bias", "biased",
                        "дрейф", "дрейфовать", "сползание", "сползать", "смещение", "смещаться", "отклонение",
                        "отклоняться", "постепенный сдвиг", "сдвиг", "расползание границ", "расширение рамок",
                        "соскальзывание", "предвзятость", "ползучий", "со временем уходит")),
    "VARIATION": ("state", ("variation", "vary", "variability", "variant", "diversity", "diverse",
                            "heterogeneity", "heterogeneous", "mutation", "mutate", "distribution", "dispersion", "different", "difference", "deviation",
                            "вариация", "вариативность", "изменчивость", "разброс", "дисперсия", "разнообразие",
                            "разнородность", "неоднородность", "разный", "различие", "отличие", "мутация",
                            "мутировать", "распределение", "вариант", "разновидность", "по-разному")),
    "SELECTION": ("mechanism", ("select", "selection", "filter", "filtering", "screen", "screening",
                                "prune", "pruning", "cull", "weed out", "triage", "prioritize",
                                "prioritization", "rank", "ranking", "choose", "choice", "pick",
                                "survival", "survive", "winnow", "gating", "triage routine",
                                "отбор", "отбирать", "отбраковка", "выбор", "выбирать", "выбрать", "фильтр",
                                "фильтрация", "фильтровать", "отсев", "отсеивать", "прополка", "отсечение",
                                "сортировка", "сортировать", "приоритизация", "расстановка приоритетов",
                                "ранжирование", "ранжировать", "триаж", "выживание", "выживать")),
    "ADAPTATION": ("mechanism", ("adapt", "adaptation", "adjust", "adjustment", "tune", "tuning",
                                 "calibrate", "calibration", "learn", "learning", "evolve", "evolution",
                                 "iterate", "iteration", "improve", "improvement", "optimize",
                                 "optimization", "refine", "refinement", "retrain", "fine-tune",
                                 "fine tune", "correction", "correct", "compensate", "compensation",
                                 "адаптация", "адаптировать", "приспособление", "приспосабливаться", "подстройка",
                                 "подстраивать", "настройка", "настраивать", "регулировка", "калибровка",
                                 "калибровать", "обучение", "учиться", "эволюция", "эволюционировать", "итерация",
                                 "улучшение", "улучшать", "оптимизация", "оптимизировать", "доработка",
                                 "дорабатывать", "уточнение", "переобучение", "тонкая настройка", "корректировка",
                                 "корректировать", "коррекция", "компенсация", "компенсировать")),
    "MEMORY": ("resource", ("memory", "remember", "recall", "retention", "retain", "record", "history",
                            "log", "archive", "cache", "store", "storage", "persist", "persistence",
                            "snapshot", "checkpoint", "journal", "ledger", "biobank", "repository", "warehouse of", "span store", "trace store", "case file", "dossier",
                            "память", "помнить", "запоминать", "запомнить", "вспоминать", "воспоминание",
                            "удержание", "запись", "записи", "история", "журнал", "архив", "кеш", "кэш", "хранение",
                            "хранилище", "хранить", "сохранение", "сохранять", "снимок", "контрольная точка",
                            "картотека", "досье", "летопись", "биобанк", "архивы")),
    "FORGETTING": ("state", ("forget", "forgetting", "amnesia", "lose track", "lost", "loss of context",
                             "context loss", "evict", "eviction", "expire", "stale", "staleness",
                             "outdated", "obsolete", "decay of memory", "fade", "fading",
                             "забывание", "забывать", "забыть", "забвение", "амнезия", "потеря контекста",
                             "потеря памяти", "упустить", "упускать из виду", "вытеснение", "вытеснять",
                             "устаревший", "устареть", "несвежий", "стирание", "стереть", "потерять нить",
                             "выпало из памяти", "вылетело из головы")),
    "ATTENTION": ("resource", ("attention", "focus", "concentration", "concentrate", "awareness",
                               "vigilance", "alertness", "mindshare", "bandwidth of", "cognitive load",
                               "notice", "noticing", "salience", "salient", "priority",
                               "внимание", "внимательность", "фокус", "фокусировка", "сосредоточенность",
                               "сосредоточиться", "концентрация", "концентрироваться", "бдительность",
                               "настороженность", "осознанность", "когнитивная нагрузка", "умственная нагрузка",
                               "заметить", "замечать", "значимость", "приоритет", "важность")),
    "FATIGUE": ("state", ("fatigue", "tired", "tiredness", "exhausted", "burnout", "burn out", "burned out",
                          "weary", "weariness", "overworked", "drained", "depleted energy", "alert fatigue",
                          "decision fatigue", "worn down",
                          "усталость", "устать", "уставать", "утомление", "утомляемость", "изнеможение",
                          "измотанность", "измотан", "выгорание", "выгореть", "перегорание", "перегореть",
                          "вымотанный", "обессиленный", "переутомление", "надорваться", "без сил",
                          "усталость от оповещений", "усталость от решений")),
    "MOTIVATION": ("state", ("motivation", "motivate", "incentive", "incentivize", "reward", "drive",
                             "morale", "engagement", "engaged", "enthusiasm", "commitment", "willingness",
                             "desire", "goal", "ambition", "encourage", "encouragement", "discourage",
                             "мотивация", "мотивировать", "стимул", "стимулировать", "поощрение", "поощрять",
                             "вознаграждение", "награда", "побуждение", "моральный дух", "вовлеченность", "вовлечен",
                             "энтузиазм", "заинтересованность", "приверженность", "готовность", "желание",
                             "стремление", "амбиция", "воодушевление", "подбадривать", "демотивация",
                             "обескураживать", "интерес")),
    "TRUST": ("state", ("trust", "trusted", "confidence", "credibility", "credible", "reputation",
                        "reliability", "reliable", "faith", "legitimacy", "assurance", "distrust",
                        "mistrust", "suspicion", "suspicious", "skepticism", "sceptic",
                        "доверие", "доверять", "доверенный", "уверенность", "надежность", "репутация", "авторитет",
                        "достоверность", "добросовестность", "вера", "легитимность", "гарантия", "недоверие",
                        "подозрение", "подозрительность", "скепсис", "скептицизм")),
    "RISK": ("state", ("risk", "risky", "hazard", "hazardous", "danger", "dangerous", "threat", "exposure",
                       "vulnerable", "vulnerability", "fragile", "fragility", "liability", "peril",
                       "jeopardy", "susceptible", "susceptibility", "attack surface", "weakness",
                       "риск", "рискованный", "опасность", "угроза", "угрожать", "уязвимость", "хрупкость",
                       "хрупкий", "подверженность", "подвержен", "незащищенность", "слабое место", "слабость",
                       "поверхность атаки", "чревато", "под ударом")),
    "DEBT": ("state", ("debt", "technical debt", "tech debt", "liability", "owe", "arrears", "borrow",
                       "borrowing", "leverage", "leveraged", "margin", "margin call", "loan", "credit",
                       "deferred cost", "shortcut", "shortcuts", "kludge", "hack", "skipping", "skip", "skipped", "deferred", "defer", "deferral", "sleep debt", "cut corners", "corner cutting", "quick fix", "quick fixes", "quick hack", "quick hacks", "hacks", "workaround", "workarounds", "skipping maintenance", "postponed maintenance",
                       "долг", "задолженность", "обязательство", "займ", "кредит", "брать в долг", "занимать",
                       "технический долг", "техдолг", "плечо", "маржа", "маржинальное требование",
                       "отложенные затраты", "костыль", "костыли", "хак", "обходной путь", "обходное решение",
                       "временное решение", "срезать углы", "срезание углов", "быстрое решение", "недосып",
                       "дефицит сна", "недоделка", "отложенное обслуживание", "отложенный ремонт",
                       "пропущенное обслуживание")),
    "INVESTMENT": ("method", ("invest", "investment", "fund", "funding", "spend", "spending", "allocate",
                              "allocation", "commit resources", "capital", "effort", "put in", "input",
                              "upfront cost", "sunk cost", "pay down", "paying down", "repay", "repayment", "rest days", "catch up rest", "catch-up", "catch up", "planned maintenance", "maintenance investment",
                              "инвестиция", "инвестировать", "вложение", "вкладывать", "вложить", "капиталовложение",
                              "выделение ресурсов", "выделять ресурсы", "усилие", "первоначальные затраты",
                              "невозвратные затраты", "погашение долга", "погашать", "выплата", "выплачивать",
                              "возврат долга", "дни отдыха", "восстановительный отдых", "плановое обслуживание",
                              "профилактическое обслуживание", "вкладывать силы")),
    "SURGE_EVENT": ("state", ("burst", "surge", "spike", "rush", "stampede", "run on", "wave", "flood",
                              "influx", "flurry", "selloff", "sell-off", "sell off", "fire sale",
                              "panic selling", "panic buying", "frenzy", "swarm", "onslaught", "deluge",
                              "sudden demand", "thundering herd", "storm", "retry storm",
                              "всплеск", "скачок", "ажиотаж", "ажиотажный спрос", "волна", "шквал", "буря", "шторм",
                              "паническая продажа", "паническая скупка", "массовая распродажа", "сброс активов",
                              "внезапный спрос", "толчея", "столпотворение", "нашествие", "хлынуть")),
    # ---- outcomes ---------------------------------------------------------
    "FAILURE": ("outcome", ("fail", "failure", "failing", "collapse", "collapsed", "crash", "crashed",
                            "outage", "breakdown", "break", "broken", "death", "die", "dying", "loss",
                            "lose", "ruin", "wreck", "meltdown", "blackout", "downtime", "shutdown",
                            "shut down", "bankrupt", "bankruptcy", "insolvency", "insolvent", "default",
                            "catastrophe", "catastrophic", "disaster", "abort", "aborted", "dropout",
                            "drop out", "give up", "quit", "extinction", "demise", "unavailable", "closure", "wipeout", "wipe out", "crisis", "damage", "damaged", "harm", "injury", "fall behind", "falling behind", "lose ground", "losing ground", "missed sla", "sla breach",
                            "отказ", "отказать", "провал", "провалиться", "неудача", "крах", "крушение", "обвал",
                            "обрушение", "рухнуть", "авария", "аварийный", "поломка", "сломаться", "простой",
                            "недоступность", "недоступен", "отключение", "блэкаут", "банкротство", "банкрот",
                            "несостоятельность", "дефолт", "катастрофа", "катастрофический", "бедствие", "гибель",
                            "гибнуть", "смерть", "умирать", "потеря", "утрата", "ущерб", "вред", "повреждение",
                            "травма", "вымирание", "закрытие", "отставание", "отстать")),
    "SUCCESS": ("outcome", ("succeed", "success", "successful", "win", "winning", "achieve", "achievement",
                            "accomplish", "goal met", "complete",
                            "completion", "finish", "thrive", "thriving", "flourish", "prosper",
                            "prosperity", "victory", "healthy", "health",
                            "успех", "успешный", "преуспеть", "победа", "выигрыш", "выиграть", "достижение",
                            "достичь", "достигать", "выполнение", "выполнить", "завершение", "завершить", "готово",
                            "процветание", "процветать", "расцвет", "здоровый", "благополучие")),
    "RECOVERY": ("outcome", ("recover", "recovery", "restore", "restoration", "heal", "healing", "repair",
                             "rebuild", "rebound", "bounce back", "resume", "resumption", "revive",
                             "revival", "rehabilitate", "remediate", "remediation", "fix", "fixed",
                             "roll back", "rollback", "reset", "restart", "reboot", "mttr", "time to recover", "faster recovery", "bounce-back",
                             "восстановление", "восстановить", "восстанавливаться", "выздоровление", "выздороветь",
                             "заживление", "заживать", "ремонт", "чинить", "починить", "отремонтировать",
                             "исправление", "исправить", "налаживание", "наладить", "реабилитация", "возобновление",
                             "возобновить", "возрождение", "оживление", "отскок", "откат", "сброс", "перезапуск",
                             "перезапустить", "перезагрузка", "перезагрузить", "время восстановления",
                             "приходить в себя")),
    "RESILIENCE": ("state", ("resilient", "resilience", "robust", "robustness", "durable", "durability",
                             "hardy", "tolerant", "tolerance", "fault tolerant", "fault-tolerant",
                             "graceful degradation", "withstand", "endure", "endurance", "survivable",
                             "antifragile", "sturdy",
                             "живучесть", "жизнестойкость", "отказоустойчивость", "устойчивый к сбоям",
                             "стрессоустойчивость", "прочность", "прочный", "крепкий", "выносливость", "выдерживать",
                             "выдержать", "стойкость", "стойкий", "долговечность", "плавная деградация",
                             "антихрупкость", "терпимость к сбоям", "не разваливается")),
    "STABILITY": ("state", ("stable", "stability", "steady", "steady state", "equilibrium", "balance",
                            "balanced", "homeostasis", "settle", "settled", "converge", "convergence",
                            "consistent", "calm", "constant", "level",
                            "стабильность", "устойчивость", "равновесие", "баланс", "сбалансированный", "гомеостаз",
                            "установившийся режим", "стационарный", "постоянство", "постоянный", "ровный",
                            "спокойный", "спокойствие", "успокоиться", "сходимость", "сходиться", "улечься",
                            "неизменный", "выйти на плато")),
    "QUALITY": ("state", ("quality", "accuracy", "accurate", "precision", "precise", "fidelity",
                          "correctness", "integrity", "soundness", "reliability", "performance",
                          "effectiveness", "efficacy", "efficiency", "efficient",
                          "качество", "качественный", "точность", "точный", "аккуратность", "верность",
                          "корректность", "целостность", "добротность", "исправность", "производительность",
                          "результативность", "эффективность")),
    "EFFICIENCY_LOSS": ("problem", ("waste", "wasted", "wasteful", "inefficient", "inefficiency",
                                    "overhead", "rework", "duplication", "duplicate effort", "churn",
                                    "thrash", "thrashing", "idle", "idling", "underutilized", "redundant tests", "redundant work", "double work", "duplicated effort", "duplicate work", "repeated work", "wasted rework", "wasted demolition",
                                    "впустую", "трата впустую", "растрата", "расточительство", "расточительный",
                                    "неэффективность", "накладные расходы", "переделка", "переделывать",
                                    "дублирование усилий", "двойная работа", "повторная работа", "лишняя работа",
                                    "холостой ход", "холостая работа", "буксование", "топтание на месте",
                                    "напрасный труд", "недоиспользование", "недозагрузка", "суета", "метания",
                                    "зря потраченное время")),
    # ---- epistemic / methods ---------------------------------------------
    "EVIDENCE": ("evidence", ("data", "dataset", "proof", "prove", "finding", "findings",
                              "observation", "observed", "experiment", "experimental",
                              "measurement", "measured", "study", "survey", "sample", "statistic",
                              "statistics", "record", "log entry", "report", "trace", "audit trail",
                              "benchmark", "test result", "slide", "specimen", "sherd", "witness statement", "statement", "testimony", "satellite", "station record", "bank record", "call record", "field data", "survey data", "readout", "sample data",
                              "данные", "набор данных", "доказательство", "доказать", "факт", "свидетельство",
                              "свидетельские показания", "наблюдение", "наблюдать", "эксперимент", "замер",
                              "исследование", "опрос", "выборка", "образец", "проба", "статистика",
                              "статистические данные", "протокол испытаний", "результаты теста", "полевые данные",
                              "архивные данные", "выписка", "первичные данные")),
    "HYPOTHESIS": ("problem", ("hypothesis", "hypothesize", "conjecture", "assumption", "assume",
                               "theory", "premise", "claim", "proposition", "guess", "expectation",
                               "expect", "prediction", "predict", "belief", "believe", "suspect",
                               "гипотеза", "предположение", "предполагать", "допущение", "допускать", "догадка",
                               "теория", "посылка", "утверждение", "версия", "ожидать", "прогноз", "прогнозировать",
                               "предсказание", "предсказывать", "убеждение", "подозревать")),
    "MODEL": ("method", ("model", "modeling", "modelling", "simulation", "simulate", "representation",
                         "abstraction", "schema", "framework", "mapping", "diagram", "formula",
                         "equation", "algorithm", "estimator", "estimate", "approximation", "bayesian", "statistical model", "estimation", "ensemble", "chronology", "timeline", "attribution ensemble",
                         "модель", "моделирование", "моделировать", "симуляция", "симулировать", "имитация",
                         "представление", "абстракция", "схема", "каркас", "фреймворк", "отображение", "диаграмма",
                         "формула", "уравнение", "алгоритм", "оценка", "оценивать", "приближение", "аппроксимация",
                         "байесовский", "статистическая модель", "ансамбль", "хронология", "упрощенная картина")),
    "METHOD": ("method", ("methodology", "technique", "approach", "strategy", "tactic",
                          "procedure", "protocol", "process", "practice", "routine", "recipe", "playbook",
                          "policy", "rule", "heuristic", "workflow", "pipeline", "scheme",
                          "plan", "planning", "design", "architecture", "solution", "intervention",
                          "treatment", "therapy", "regimen", "remedy", "countermeasure", "safeguard",
                          "методика", "методология", "способ", "подход", "стратегия", "тактика", "процедура",
                          "протокол", "процесс", "практика", "рутина", "рецепт", "регламент", "политика", "правило",
                          "эвристика", "рабочий процесс", "план", "планирование", "планировать", "дизайн",
                          "архитектура", "решение", "вмешательство", "лечение", "терапия", "режим", "контрмера",
                          "мера", "порядок действий", "инструкция", "режимы")),
    "TOOL": ("resource", ("tool", "tooling", "instrument", "device", "equipment", "machine", "machinery",
                          "apparatus", "software", "library", "platform", "infrastructure", "system",
                          "service", "utility", "facility", "hardware",
                          "инструмент", "инструментарий", "прибор", "устройство", "оборудование", "аппарат",
                          "аппаратура", "техника", "машина", "программа", "программное обеспечение", "софт",
                          "библиотека", "платформа", "инфраструктура", "система", "сервис", "служба", "утилита",
                          "железо", "оснастка")),
    "RESOURCE": ("resource", ("supply", "supplies", "inventory", "stock",
                              "asset", "assets", "material", "materials", "input", "inputs", "raw material",
                              "fuel", "energy", "power", "water", "food", "staff", "personnel", "labor",
                              "labour", "manpower", "headcount", "compute", "storage space", "roster", "pool", "credit line", "line of credit", "credit facility", "vessel time", "ship time", "cluster time", "compute time", "lab time", "machine time", "beam time", "zone", "reserve zone", "protected area", "sanctuary", "set aside", "land set aside",
                              "снабжение", "поставки", "припасы", "товарные запасы", "сырье", "материал",
                              "материалы", "комплектующие", "топливо", "энергия", "электроэнергия", "вода",
                              "продовольствие", "персонал", "кадры", "рабочая сила", "штат", "численность персонала",
                              "вычислительные ресурсы", "машинное время", "лабораторное время", "время на кластере",
                              "судовое время", "дисковое пространство", "место для хранения", "пул",
                              "кредитная линия", "охранная зона", "заповедник", "заказник", "резервная зона")),
    "INFORMATION": ("resource", ("information", "info", "knowledge", "insight", "context", "documentation",
                                 "document", "docs", "message", "messages", "communication", "communicate",
                                 "news", "update", "updates", "notification", "report", "reporting",
                                 "signal", "feed", "content", "email", "emails", "chat", "meeting",
                                 "meetings", "memo", "spec", "specification",
                                 "информация", "сведения", "знание", "инсайт", "понимание", "контекст",
                                 "документация", "документ", "сообщение", "коммуникация", "общение", "новости",
                                 "обновление", "уведомление", "отчет", "отчетность", "лента", "контент",
                                 "содержание", "почта", "письмо", "чат", "переписка", "встреча", "совещание",
                                 "записка", "спецификация", "техзадание")),
    "REQUEST": ("state", ("request", "requests", "query", "queries", "call", "calls", "ask", "order",
                          "orders", "demand", "ticket", "tickets", "job", "jobs", "task", "tasks",
                          "transaction", "transactions", "submission", "application", "claim", "claims",
                          "inquiry", "inquiries", "customer", "customers", "user", "users", "patient",
                          "patients", "client", "clients", "visitor", "visitors",
                          "запрос", "обращение", "заявка", "заказ", "звонок", "звонки", "вызов", "вызовы", "просьба",
                          "тикет", "задача", "задание", "транзакция", "операция", "заявление", "претензия", "клиент",
                          "пользователь", "пациент", "посетитель", "покупатель", "абонент")),
    "RETRY": ("mechanism", ("retry", "retries", "retrying", "re-try", "resend", "repeat", "repeated",
                            "repetition", "reattempt", "again", "redo", "resubmit", "reissue",
                            "loop back", "keep trying", "try again", "polling", "poll", "repeatedly", "again and again", "re present", "re send", "re try", "re submit", "come back", "coming back", "return visit", "return visits",
                            "повтор", "повторение", "повторять", "повторный", "повторные попытки", "попытка",
                            "ретрай", "переотправка", "переотправить", "отправить заново", "заново", "снова",
                            "снова и снова", "опять", "перезапрос", "дозвон", "дозваниваться", "циклический опрос",
                            "возвращаться", "повторное обращение", "повторный визит")),
    "TIMEOUT": ("state", ("timeout", "time out", "timed out", "expire", "expired", "expiry", "deadline miss",
                          "missed deadline", "give up waiting", "abandon", "abandonment", "drop",
                          "dropped", "cancel", "cancellation", "walk away", "churn", "missed sla", "sla breach", "sla miss", "missed target", "missed slot",
                          "таймаут", "истечение времени", "время истекло", "срыв срока", "пропущенный срок",
                          "не дождаться", "перестать ждать", "отказ от ожидания", "бросить", "бросать", "отмена",
                          "отменить", "аннулирование", "отток клиентов", "ушел не дождавшись", "пропущенный слот",
                          "неявка", "так и не дождались")),
    "THRESHOLD_EVENT": ("state", ("trigger", "triggered", "trip", "tripped", "breach", "breached", "cross",
                                  "crossing", "exceed", "exceeded", "violate", "violation", "overrun",
                                  "overstep", "hit the limit", "reach the limit", "critical", "spill point", "passing the", "past the", "beyond the", "over the line", "breaching",
                                  "превышение", "превысить", "превышать", "срабатывание", "сработать", "триггер",
                                  "спусковой крючок", "пересечение порога", "перейти порог", "переход через порог",
                                  "нарушение", "нарушить", "выход за пределы", "за пределами", "выше порога",
                                  "критический", "критическая отметка", "зашкаливать", "преодолеть порог",
                                  "перевалить за")),
    "CONTROL": ("method", ("control", "controller", "regulate", "regulation", "regulator", "govern",
                           "governance", "throttle", "throttling", "rate limiting", "limiter", "valve",
                           "brake", "braking", "moderate", "moderation", "manage", "management",
                           "supervise", "supervision", "oversight", "steer", "steering", "thermostat",
                           "circuit breaker", "breaker", "backoff", "back off", "back-off", "shed load",
                           "load shedding", "admission control", "quota enforcement", "cap enforcement", "liquidation", "liquidate", "stop loss", "stop-loss", "kill switch", "shutoff", "shut off", "automatic shutdown", "pump", "dosing", "release valve", "controlled release", "halt rule", "trading halt",
                           "управление", "управлять", "контроль", "контролировать", "регулирование", "регулировать",
                           "регулятор", "надзор", "надзирать", "руководство", "руководить", "дросселирование",
                           "дроссель", "ограничитель", "клапан", "вентиль", "тормоз", "торможение", "модерация",
                           "модерировать", "сдерживание", "сдерживать", "руль", "штурвал", "направлять", "термостат",
                           "автоматический выключатель", "предохранитель", "аварийное отключение",
                           "аварийный останов", "сброс нагрузки", "квотирование", "ликвидация позиции", "стоп-лосс",
                           "дозирование", "дозировать", "насос", "выпускной клапан", "остановка торгов",
                           "держать в узде")),
    "BLOCKING_ACTION": ("method", ("prevent", "prevention", "block", "stop", "halt", "avoid", "avoidance",
                                   "forbid", "prohibit", "prohibition", "ban", "veto", "reject", "rejection",
                                   "deny", "denial", "refuse", "refusal", "inhibit", "inhibition",
                                   "deter", "deterrent", "guard", "shield", "protect", "protection",
                                   "defend", "defense", "defence", "immunize", "immunity", "vaccinate",
                                   "предотвращение", "предотвращать", "предотвратить", "недопущение", "не допустить",
                                   "пресечение", "пресекать", "блокирование", "профилактика", "запрет", "запрещать",
                                   "вето", "отказ в доступе", "недопуск", "препятствовать", "помешать", "мешать",
                                   "защита", "защищать", "оборона", "щит", "экранирование", "иммунитет",
                                   "иммунизация", "вакцинация", "прививка", "избегать", "избежать", "избегание",
                                   "уклонение")),
    "ENABLING_ACTION": ("method", ("enable", "enabling", "allow", "permit", "unlock", "facilitate",
                                   "facilitation", "support", "supporting", "empower", "grant", "authorize",
                                   "authorization", "license", "open up", "make possible", "afford",
                                   "разрешение", "разрешать", "разрешить", "позволить", "позволять", "включение",
                                   "включить", "активация", "активировать", "разблокировка", "разблокировать",
                                   "открыть доступ", "дать доступ", "содействие", "содействовать", "способствовать",
                                   "поддержка", "поддерживать", "обеспечить", "наделить полномочиями", "полномочия",
                                   "лицензия", "санкционировать", "одобрение", "одобрить", "сделать возможным",
                                   "открыть путь", "упрощение", "упростить", "облегчить")),
    "TESTING": ("method", ("test", "testing", "verify", "verification", "validate", "validation", "check",
                           "checking", "inspect", "inspection", "review", "audit", "assess", "assessment",
                           "evaluate", "evaluation", "diagnose", "diagnosis", "diagnostic", "probe",
                           "screen", "examine", "examination", "trial", "pilot", "canary", "rehearsal",
                           "dry run", "drill", "experiment", "experimental", "benchmark", "benchmark run", "a b", "a/b", "culture test", "blood test", "lab test", "field trial", "survey pilot", "survey", "sequencing", "assay", "panel", "tracing", "trace analysis", "profiling", "reanalysis", "attribution", "reconstruction", "dating", "typology", "interview", "cross-examination", "cross examination", "discovery process",
                           "тест", "тестирование", "тестировать", "проверка", "проверять", "проверить", "испытание",
                           "испытывать", "верификация", "валидация", "осмотр", "осматривать", "инспекция", "ревизия",
                           "аудит", "экспертиза", "обследование", "диагностика", "диагностировать", "диагноз",
                           "анализ", "анализировать", "зонд", "зондирование", "скрининг", "пилот", "пилотный запуск",
                           "пробный запуск", "репетиция", "тренировка", "прогон", "сухой прогон",
                           "канареечный запуск", "бенчмарк", "эталонный тест", "сплит-тест", "анализ крови",
                           "лабораторный анализ", "полевое испытание", "секвенирование", "датировка",
                           "реконструкция", "допрос", "перекрестный допрос")),
    # ---- agents / social ----------------------------------------------------
    "AGENT": ("agent", ("person", "people", "team", "teams", "individual", "employee", "employees",
                        "worker", "workers", "manager", "managers", "leader", "leadership", "engineer",
                        "engineers", "developer", "developers", "operator", "operators", "doctor",
                        "nurse", "clinician", "staff", "crew", "organization", "organisation", "company",
                        "firm", "department", "group", "community", "population", "society", "government",
                        "agency", "committee", "board", "founder", "founders", "student", "students",
                        "teacher", "family", "household", "actor", "actors", "participant", "participants",
                        "stakeholder", "stakeholders", "member", "members", "bank",
                        "banks", "investor", "investors", "trader", "traders", "market participant", "fleet", "clinic", "clinics", "desk", "application", "applications", "vendor", "vendors", "supplier", "suppliers", "trawler", "subcontractor", "subcontractors",
                        "человек", "люди", "команда", "коллектив", "сотрудник", "работник", "руководитель",
                        "менеджер", "лидер", "лидерство", "инженер", "разработчик", "оператор", "врач", "медсестра",
                        "клиницист", "экипаж", "бригада", "организация", "компания", "фирма", "отдел",
                        "подразделение", "группа", "сообщество", "население", "общество", "правительство",
                        "ведомство", "комитет", "совет", "основатель", "студент", "учитель", "преподаватель",
                        "семья", "домохозяйство", "участник", "заинтересованная сторона", "стейкхолдер", "член",
                        "банк", "инвестор", "трейдер", "поставщик", "подрядчик", "субподрядчик", "клиника")),
    "INCENTIVE_MISMATCH": ("problem", ("moral hazard", "perverse incentive", "misaligned incentive",
                                       "free rider", "free-rider", "tragedy of the commons", "gaming",
                                       "game the", "goodhart", "principal agent", "principal-agent",
                                       "conflict of interest", "rent seeking", "rent-seeking",
                                       "моральный риск", "ложные стимулы", "извращенные стимулы", "перекос стимулов",
                                       "безбилетник", "халявщик", "трагедия общин", "накрутка",
                                       "накрутка показателей", "игра с показателями", "закон гудхарта",
                                       "конфликт интересов", "погоня за рентой", "рентоориентированное поведение",
                                       "проблема принципала", "принципал агент", "работа на показатель",
                                       "каждый тянет на себя")),
    "COMMUNICATION_GAP": ("problem", ("miscommunication", "misunderstanding", "misunderstand", "unclear",
                                      "ambiguous instruction", "lost in translation", "silence",
                                      "no visibility", "opaque", "opacity", "hidden", "invisible",
                                      "blind spot", "unaware", "ignorance", "ignorant", "out of the loop",
                                      "information asymmetry", "asymmetry", "notes missing", "information lost", "missing handoff", "not passed along", "not passed on", "not communicated", "never told", "no one told", "unshared", "not shared", "uninformed", "hidden changes", "hidden change", "nothing passed on",
                                      "недопонимание", "непонимание", "недосказанность", "искажение при передаче",
                                      "потеря при передаче", "молчание", "замалчивание", "непрозрачность",
                                      "скрытность", "скрытый", "невидимый", "слепая зона", "слепое пятно",
                                      "неведение", "не в курсе", "не знал", "никто не сказал", "не сообщили",
                                      "не передали", "не предупредили", "информационная асимметрия",
                                      "асимметрия информации", "разрыв в коммуникации", "потерянные заметки",
                                      "отсутствие информации", "нет информации")),
    # ---- generic problem / goal words (weak, role-carrying) ----------------
    "PROBLEM": ("problem", ("issue", "trouble", "difficulty", "difficult", "challenge",
                            "obstacle", "pain", "pain point", "friction point", "concern", "worry",
                            "complaint", "symptom", "incident", "crisis", "emergency", "bottleneck", "disease", "blight", "infection", "outbreak", "bad loan", "bad debt", "nonperforming", "non performing",
                            "трудность", "трудный", "сложность", "затруднение", "беда", "неприятность",
                            "препятствие", "преграда", "болевая точка", "жалоба", "инцидент", "происшествие",
                            "кризис", "чрезвычайная ситуация", "аврал", "заболевание", "болезнь", "недуг",
                            "вспышка заболевания", "беспокойство", "опасение", "безнадежный долг",
                            "просроченный кредит", "что-то не так")),
    "GOAL": ("outcome", ("goal", "objective", "target", "aim", "purpose", "intent", "intention", "mission",
                         "result", "desired", "want", "wanted", "need to", "should", "must",
                         "milestone", "deliverable", "kpi", "okr", "metric of success",
                         "цель", "целевой", "назначение", "намерение", "замысел", "задумка", "миссия", "результат",
                         "итог", "желаемое", "веха", "ориентир", "целевой показатель", "плановый показатель",
                         "поставленная цель")),
    # ---- domain anchors: same-domain support only, no analogical weight ----
    "DOMAIN_ELECTROCHEMISTRY": (None, ("battery", "batteries", "cell", "cells", "electrolyte", "anode",
                                       "cathode", "lithium", "li-ion", "charge", "charging", "discharge",
                                       "voltage", "current", "resistance", "ohm", "capacity fade",
                                       "dendrite", "dendrites", "electrode", "separator", "pack",
                                       "батарея", "батареи", "аккумулятор", "аккумуляторная батарея",
                                       "элемент питания", "электролит", "анод", "катод", "литий", "литий-ионный",
                                       "заряд", "зарядка", "разряд", "разрядка", "электрическое напряжение", "ток",
                                       "сила тока", "омическое сопротивление", "электрод", "сепаратор", "дендрит",
                                       "дендриты", "деградация емкости", "ячейка", "батарейный блок")),
    "DOMAIN_SOFTWARE": (None, ("server", "servers", "service", "microservice", "api", "database", "db",
                               "cache", "queue", "cluster", "node", "pod", "container", "deploy",
                               "deployment", "release", "commit", "merge", "pull request", "code",
                               "codebase", "bug", "latency", "cpu", "memory", "disk", "network", "packet",
                               "thread", "process", "lock", "mutex", "garbage collection", "gc",
                               "connection pool", "retry storm", "thundering herd",
                               "сервер", "микросервис", "интерфейс", "база данных", "бд", "кеш", "кэш", "очередь",
                               "кластер", "узел", "нода", "контейнер", "деплой", "развертывание", "релиз", "коммит",
                               "мерж", "слияние", "пул-реквест", "код", "кодовая база", "баг", "процессор", "цпу",
                               "оперативная память", "диск", "сеть", "пакет", "поток", "процесс", "мьютекс",
                               "сборка мусора", "пул соединений", "шторм повторов")),
    "DOMAIN_FINANCE": (None, ("market", "markets", "stock", "stocks", "asset", "price", "prices", "trader",
                              "traders", "bank", "banks", "loan", "loans", "credit", "liquidity", "margin",
                              "margin call", "collateral", "selloff", "sell-off", "sell off", "deposit",
                              "deposits", "withdrawal", "withdrawals", "portfolio", "investor", "investors",
                              "bond", "bonds", "interest rate", "inflation", "currency", "leverage",
                              "рынок", "рынки", "акция", "актив", "активы", "цена", "трейдер", "банк", "кредит",
                              "кредиты", "ликвидность", "маржа", "маржин-колл", "залог", "распродажа", "депозит",
                              "депозиты", "вклад", "вкладчик", "снятие", "вывод средств", "портфель", "инвестор",
                              "облигация", "процентная ставка", "инфляция", "валюта", "кредитное плечо", "биржа",
                              "котировка")),
    "DOMAIN_ORGANIZATION": (None, ("team", "teams", "organization", "organisation", "company", "manager",
                                   "management", "meeting", "meetings", "hiring", "onboarding", "process",
                                   "department", "headcount", "roadmap", "priority", "priorities",
                                   "stakeholder", "decision", "decisions", "reorg", "reorganization",
                                   "команда", "организация", "компания", "менеджер", "менеджмент", "руководство",
                                   "совещание", "встреча", "найм", "онбординг", "адаптация новичков", "процесс",
                                   "отдел", "департамент", "штат", "численность", "дорожная карта", "роадмап",
                                   "приоритет", "стейкхолдер", "принятие решений", "реорганизация", "реорг",
                                   "планерка", "корпоративный")),
    "DOMAIN_MEDICINE": (None, ("patient", "patients", "hospital", "clinic", "doctor", "nurse", "clinician",
                               "diagnosis", "treatment", "therapy", "dose", "dosage", "drug", "medication",
                               "symptom", "symptoms", "infection", "immune", "immune system", "inflammation",
                               "tumor", "tumour", "blood", "heart", "cardiac", "kidney", "liver", "cell",
                               "cells", "virus", "bacteria", "antibiotic", "resistance to antibiotics",
                               "пациент", "больница", "клиника", "врач", "медсестра", "клиницист", "диагноз",
                               "лечение", "терапия", "доза", "дозировка", "лекарство", "препарат", "медикамент",
                               "симптом", "инфекция", "воспаление", "иммунитет", "иммунная система", "опухоль",
                               "кровь", "сердце", "сердечный", "почка", "печень", "клетка", "вирус", "бактерии",
                               "антибиотик", "устойчивость к антибиотикам", "палата")),
    "DOMAIN_ECOLOGY": (None, ("ecosystem", "species", "population", "predator", "prey", "habitat",
                              "biodiversity", "forest", "fishery", "fish", "overfishing", "soil",
                              "nutrient", "nutrients", "algae", "bloom", "river", "lake", "ocean", "climate",
                              "drought", "rainfall", "crop", "crops", "harvest", "farm", "farming",
                              "livestock", "grazing", "pasture",
                              "экосистема", "вид", "популяция", "хищник", "жертва", "добыча", "среда обитания",
                              "биоразнообразие", "лес", "рыболовство", "рыба", "перелов", "почва",
                              "питательные вещества", "водоросли", "цветение водорослей", "река", "озеро", "океан",
                              "климат", "засуха", "осадки", "урожай", "посев", "ферма", "сельское хозяйство", "скот",
                              "выпас", "пастбище", "угодья")),
    "DOMAIN_INFRASTRUCTURE": (None, ("bridge", "road", "roads", "highway", "traffic", "grid", "power grid",
                                     "transformer", "substation", "pipe", "pipes", "pipeline", "water supply",
                                     "sewer", "reservoir", "dam", "levee", "rail", "railway", "train",
                                     "airport", "runway", "port", "harbor", "harbour", "warehouse",
                                     "supply chain", "logistics", "shipping", "container ship", "truck",
                                     "мост", "дорога", "шоссе", "трасса", "трафик", "энергосеть", "электросеть",
                                     "трансформатор", "подстанция", "труба", "трубопровод", "водоснабжение",
                                     "канализация", "водохранилище", "плотина", "дамба", "рельсы", "железная дорога",
                                     "поезд", "аэропорт", "взлетная полоса", "порт", "гавань", "склад",
                                     "цепочка поставок", "логистика", "перевозки", "контейнеровоз", "грузовик",
                                     "шлюз")),
    "DOMAIN_EDUCATION": (None, ("student", "students", "homework", "assignment", "assignments", "exam",
                                "exams", "grade", "grades", "course", "courses", "lecture", "class",
                                "classroom", "teacher", "teachers", "school", "university", "study",
                                "studying", "procrastination", "procrastinate", "semester", "tuition",
                                "студент", "ученик", "домашнее задание", "учебное задание", "экзамен", "зачет",
                                "отметка", "балл", "курс", "лекция", "урок", "класс", "аудитория", "учитель",
                                "преподаватель", "школа", "университет", "учеба", "занятия", "прокрастинация",
                                "откладывание на потом", "семестр", "сессия", "стипендия", "плата за обучение")),
    "DOMAIN_MANUFACTURING": (None, ("factory", "plant", "assembly line", "assembly", "production line",
                                    "machine", "machines", "tooling", "defect rate", "scrap", "yield",
                                    "inventory", "supplier", "suppliers", "lead time", "batch", "batches",
                                    "shift", "shifts", "maintenance", "downtime", "conveyor", "robot",
                                    "welding", "casting", "quality control",
                                    "завод", "фабрика", "цех", "конвейер", "сборочная линия", "сборка",
                                    "производственная линия", "производство", "станок", "станки", "процент брака",
                                    "лом", "выход годного", "выработка", "складские запасы", "поставщик",
                                    "срок поставки", "партия", "смена", "техобслуживание", "обслуживание",
                                    "простой оборудования", "робот", "сварка", "контроль качества",
                                    "литейное производство")),
    "DOMAIN_SCIENCE": (None, ("research", "researcher", "laboratory", "lab", "scientist", "coral", "reef",
                              "tank", "tanks", "vessel", "field study", "paper", "publication", "journal",
                              "peer review", "sample", "samples", "specimen", "trial", "study", "experiment",
                              "исследование", "исследователь", "лаборатория", "лаба", "ученый", "коралл", "риф",
                              "аквариум", "судно", "экспедиция", "полевое исследование", "статья", "публикация",
                              "журнал", "рецензирование", "рецензия", "образец", "проба", "эксперимент",
                              "научная работа", "грант", "диссертация")),
    "DOMAIN_COOKING": (None, ("dough", "sourdough", "bread", "oven", "bake", "baking", "yeast", "starter",
                              "flour", "ferment", "fermentation", "proof", "proofing", "kitchen", "recipe",
                              "ingredient", "ingredients", "sauce", "boil", "simmer", "knead", "rise of dough",
                              "закваска", "хлеб", "печь", "духовка", "выпечка", "выпекать", "дрожжи", "мука",
                              "брожение", "бродить", "ферментация", "расстойка", "кухня", "рецепт", "ингредиент",
                              "соус", "варить", "кипятить", "тушить", "месить", "замес", "подъем теста", "опара",
                              "дрожжевое тесто")),
}

# Domain classes never carry analogical weight.
DOMAIN_PREFIX = "DOMAIN_"

# Soft neighbourhood between abstract classes: partial credit when two labels
# realise *related* relational notions (amplification ~ cascade). Symmetric.
RELATED: dict[frozenset[str], float] = {}


def _rel(a: str, b: str, w: float) -> None:
    RELATED[frozenset((a, b))] = w


for _a, _b, _w in (
    ("AMPLIFICATION", "CASCADE", 0.7), ("AMPLIFICATION", "FEEDBACK", 0.7), ("CASCADE", "FEEDBACK", 0.6),
    ("CASCADE", "SURGE_EVENT", 0.6), ("SURGE_EVENT", "LOAD", 0.6), ("SURGE_EVENT", "GROWTH", 0.4),
    ("ACCUMULATION", "SATURATION", 0.6), ("ACCUMULATION", "LOAD", 0.5), ("ACCUMULATION", "GROWTH", 0.5),
    ("ACCUMULATION", "DEBT", 0.4), ("SATURATION", "LOAD", 0.6), ("SATURATION", "BOTTLENECK", 0.4),
    ("DEGRADATION", "DECLINE", 0.6), ("DEGRADATION", "FAILURE", 0.5), ("DECLINE", "DEPLETION", 0.5),
    ("DEGRADATION", "FATIGUE", 0.5), ("DEGRADATION", "ERROR", 0.3), ("DEGRADATION", "QUALITY", 0.3),
    ("DEPLETION", "SCARCITY", 0.8), ("DEPLETION", "FATIGUE", 0.5), ("DEPLETION", "LEAK", 0.4),
    ("DELAY", "BLOCKAGE", 0.5), ("DELAY", "BOTTLENECK", 0.6), ("BLOCKAGE", "BOTTLENECK", 0.6),
    ("DELAY", "TIMEOUT", 0.5), ("BLOCKAGE", "FRICTION", 0.4), ("DELAY", "FRICTION", 0.4),
    ("CONTROL", "DAMPING", 0.6), ("CONTROL", "BLOCKING_ACTION", 0.5), ("DAMPING", "COOLING", 0.6),
    ("DAMPING", "REDUNDANCY", 0.4), ("DAMPING", "ISOLATION", 0.4), ("CONTROL", "LIMIT", 0.4),
    ("LIMIT", "CAPACITY", 0.6), ("LIMIT", "BUDGET", 0.5), ("LIMIT", "DEADLINE", 0.5), ("LIMIT", "SCARCITY", 0.4),
    ("CAPACITY", "RESOURCE", 0.5), ("BUDGET", "RESOURCE", 0.4), ("BUDGET", "INVESTMENT", 0.5),
    ("THRESHOLD_EVENT", "LIMIT", 0.5), ("THRESHOLD_EVENT", "SATURATION", 0.5),
    ("STRESS", "LOAD", 0.7), ("STRESS", "HEAT", 0.4), ("STRESS", "FATIGUE", 0.5), ("HEAT", "LOAD", 0.3),
    ("COUPLING", "DEPENDENCY", 0.6), ("ISOLATION", "FRAGMENTATION", 0.3), ("COUPLING", "CASCADE", 0.4),
    ("COORDINATION", "MISALIGNMENT", 0.3), ("MISALIGNMENT", "COMMUNICATION_GAP", 0.6),
    ("MISALIGNMENT", "INCENTIVE_MISMATCH", 0.5), ("FRAGMENTATION", "COMMUNICATION_GAP", 0.5),
    ("NOISE", "SIGNAL", 0.3), ("NOISE", "UNCERTAINTY", 0.5), ("ERROR", "NOISE", 0.4),
    ("SIGNAL", "EVIDENCE", 0.6), ("SIGNAL", "TESTING", 0.4), ("EVIDENCE", "TESTING", 0.5),
    ("HYPOTHESIS", "MODEL", 0.5), ("MODEL", "METHOD", 0.5), ("METHOD", "TOOL", 0.4),
    ("METHOD", "CONTROL", 0.4), ("METHOD", "ADAPTATION", 0.4), ("ADAPTATION", "SELECTION", 0.5),
    ("ADAPTATION", "RECOVERY", 0.4), ("RECOVERY", "RESILIENCE", 0.6), ("RESILIENCE", "STABILITY", 0.6),
    ("RESILIENCE", "REDUNDANCY", 0.5), ("STABILITY", "OSCILLATION", 0.3), ("OSCILLATION", "FEEDBACK", 0.4),
    ("FAILURE", "TIMEOUT", 0.4), ("FAILURE", "RISK", 0.4), ("FAILURE", "BLOCKAGE", 0.5),
    ("SATURATION", "HEAT", 0.4), ("LOAD", "BUDGET", 0.2), ("DRIFT", "DELAY", 0.3),
    ("BLOCKAGE", "LIMIT", 0.4), ("ADAPTATION", "CONTROL", 0.5), ("COORDINATION", "METHOD", 0.3),
    ("COOLING", "CONTROL", 0.5), ("GROWTH", "SATURATION", 0.5), ("DEGRADATION", "AMPLIFICATION", 0.3),
    ("FRICTION", "SATURATION", 0.3), ("AGENT", "CONTROL", 0.3), ("PROBLEM", "UNCERTAINTY", 0.4),
    ("EVIDENCE", "MEMORY", 0.4), ("HYPOTHESIS", "UNCERTAINTY", 0.5), ("TESTING", "MODEL", 0.4),
    ("DEPENDENCY", "SCARCITY", 0.3), ("LOAD", "PROBLEM", 0.3), ("DEPLETION", "DECLINE", 0.5), ("RISK", "UNCERTAINTY", 0.4),
    ("RISK", "DEBT", 0.4), ("DEBT", "INVESTMENT", 0.3), ("SUCCESS", "GOAL", 0.5), ("SUCCESS", "QUALITY", 0.4),
    ("PROBLEM", "ERROR", 0.4), ("PROBLEM", "RISK", 0.3), ("FLOW", "REQUEST", 0.4), ("FLOW", "INFORMATION", 0.3),
    ("REQUEST", "LOAD", 0.5), ("RETRY", "FEEDBACK", 0.4), ("RETRY", "AMPLIFICATION", 0.4),
    ("RETRY", "LOAD", 0.4), ("MEMORY", "FORGETTING", 0.3), ("ATTENTION", "FATIGUE", 0.3),
    ("ATTENTION", "MOTIVATION", 0.3), ("MOTIVATION", "TRUST", 0.3), ("TRUST", "RISK", 0.3),
    ("ENABLING_ACTION", "BLOCKING_ACTION", 0.2), ("EFFICIENCY_LOSS", "FRICTION", 0.5),
    ("EFFICIENCY_LOSS", "DEPLETION", 0.3), ("SELECTION", "TESTING", 0.4), ("GROWTH", "DECLINE", 0.2),
    ("LEAK", "FLOW", 0.4), ("FRICTION", "STRESS", 0.3), ("VARIATION", "DRIFT", 0.5),
    ("VARIATION", "NOISE", 0.4), ("DRIFT", "MISALIGNMENT", 0.4), ("AGENT", "COORDINATION", 0.2),
):
    _rel(_a, _b, _w)


# The nine role names themselves (problem, mechanism, state, outcome,
# constraint, method, evidence, resource, agent) are deliberately absent from
# every term list: a label that only restates its role carries no content.

# Classes that mostly restate a node's *role* (problem, method, agent, ...)
# carry little content: two labels that share only such a class have not
# been shown to be about the same notion. They count at reduced weight.
GENERIC_CLASSES: dict[str, float] = {
    "PROBLEM": 0.3, "GOAL": 0.3, "METHOD": 0.3, "AGENT": 0.3, "RESOURCE": 0.3, "TOOL": 0.3,
    "INFORMATION": 0.3, "REQUEST": 0.3, "MEMORY": 0.4, "MODEL": 0.4, "EVIDENCE": 0.5, "SIGNAL": 0.5,
    "TESTING": 0.6,
}


def class_weight(concept: str) -> float:
    return GENERIC_CLASSES.get(concept, 1.0)


def relatedness(a: str, b: str) -> float:
    if a == b:
        return 1.0
    return RELATED.get(frozenset((a, b)), 0.0)


def _phrase_key(phrase: str) -> tuple[str, ...]:
    return tuple(stem(tok) for tok in _split(phrase))


def _split(text: str) -> list[str]:
    out: list[str] = []
    cur: list[str] = []
    for ch in text.lower():
        if ch.isalnum():
            cur.append(ch)
        else:
            if cur:
                out.append("".join(cur))
                cur = []
    if cur:
        out.append("".join(cur))
    return out


def _build() -> tuple[dict[tuple[str, ...], set[str]], int, dict[str, str | None]]:
    index: dict[tuple[str, ...], set[str]] = {}
    longest = 1
    hints: dict[str, str | None] = {}
    for concept, (role_hint, terms) in CONCEPTS.items():
        hints[concept] = role_hint
        for term in terms:
            key = _phrase_key(term)
            if not key:
                continue
            index.setdefault(key, set()).add(concept)
            longest = max(longest, len(key))
    return index, longest, hints


PHRASE_INDEX, LONGEST_PHRASE, ROLE_HINTS = _build()


def is_domain_concept(concept: str) -> bool:
    return concept.startswith(DOMAIN_PREFIX)
