"""Stable public interfaces between Resonance engine components."""

from .protocols import CandidateIndex, ConfigSource, EngineFacade, Extractor, GraphValidator, StructuralVerifier, ThoughtStore
from .types import (
    INTERFACE_VERSION,
    REQUIRED_SCORE_WIRE_NAMES,
    SCORE_CONTRACT_VERSION,
    SCORE_WIRE_NAMES,
    CandidateResult,
    ConfigRef,
    RetrievalFlags,
    Contradiction,
    EdgePathMatch,
    Explanation,
    ExtractionResult,
    ItemProvenance,
    NodeMatch,
    RelationMatch,
    ResonanceHit,
    ScoreVector,
    SeedCorrespondence,
    VerifierResult,
)

__all__ = [
    "INTERFACE_VERSION",
    "REQUIRED_SCORE_WIRE_NAMES",
    "SCORE_CONTRACT_VERSION",
    "SCORE_WIRE_NAMES",
    "ConfigRef",
    "RetrievalFlags",
    "ExtractionResult",
    "SeedCorrespondence",
    "CandidateResult",
    "ItemProvenance",
    "NodeMatch",
    "RelationMatch",
    "EdgePathMatch",
    "Contradiction",
    "ScoreVector",
    "Explanation",
    "VerifierResult",
    "ResonanceHit",
    "GraphValidator",
    "Extractor",
    "ThoughtStore",
    "CandidateIndex",
    "StructuralVerifier",
    "EngineFacade",
    "ConfigSource",
]
